# Generated by Django 2.0.5 on 2018-06-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='statics/images'),
        ),
    ]
